
kzen:
  archetypes:
#    - name: KzenProjectJar-0.5.1-SNAPSHOT
#      title: "Desktop Automation"
#      description: "Visually control a browser and more - v0.5.1-SNAPSHOT"
#      url: file:///home/ao/IdeaProjects/kzen-auto/kzen-auto-jvm/build/libs/kzen-auto-jvm-0.5.1-SNAPSHOT-boot.jar

    - name: KzenProjectJar-0.18.0
      title: "Automation and Reporting"
      description: "Visually control a browser and more - v0.18.0"
      url: https://github.com/alexoooo/kzen-project/releases/download/v0.18.0/kzen-project-jvm-0.18.0.jar

    - name: KzenProjectZip-0.18.0
      title: "Automation and Reporting (with Scripting)"
      description: "Includes source code, can be used with IDE - v0.18.0"
      url: https://github.com/alexoooo/kzen-project/releases/download/v0.18.0/kzen-project-0.18.0.zip

