
kzen:
  archetypes:
    - name: KzenProjectJar-0.4.0
      title: "Desktop Automation"
      description: "Visually control a browser and more"
      url: https://github.com/alexoooo/kzen-project/releases/download/v0.4.0/kzen-project-jvm-0.4.0.jar

    - name: KzenProjectZip-0.4.0
      title: "Desktop Automation with Scripting"
      description: "Includes source code, can be used with IDE (IntelliJ, Eclipse, etc.)"
      url: https://github.com/alexoooo/kzen-project/releases/download/v0.4.0/kzen-project-0.4.0.zip

