
# TODO: use this instead of ArchetypeRepo hard coding

archetypes:
- https://github.com/alexoooo/kzen-project/releases/download/v0.0.5/kzen-project-jvm-0.0.5.jar
#- https://github.com/alexoooo/kzen-project/releases/download/v0.0.5/kzen-project-0.0.5.zip
#- https://github.com/alexoooo/kzen-project/archive/v0.0.5.zip
#- https://github.com/alexoooo/kzen-project/releases/download/v0.0.4/kzen-project-0.0.4.zip
#- https://raw.githubusercontent.com/alexoooo/kzen-repo/master/artifacts/tech/kzen/project/kzen-project/0.0.1/kzen-project-0.0.1.zip

