
kzen:
  archetypes:
#    - name: KzenProjectJar-24.0
#      title: "Desktop Automation"
#      description: "Visually control a browser and more - v0.24.0"
##      url: file:///home/ao/IdeaProjects/kzen-auto/kzen-auto-jvm/build/libs/kzen-auto-jvm-0.5.1-SNAPSHOT-boot.jar
#      url: file:///C:/Users/ao/IdeaProjects/kzen-project/kzen-project-jvm/build/libs/kzen-project-jvm-0.24.0.jar

#    - name: KzenProjectJar-0.19.0
#      title: "Automation and Reporting"
#      description: "Visually control a browser and more - v0.19.0"
#      url: https://github.com/alexoooo/kzen-project/releases/download/v0.19.0/kzen-project-jvm-0.19.0.jar
#
#    - name: KzenProjectZip-0.19.0
#      title: "Automation and Reporting (with Scripting)"
#      description: "Includes source code, can be used with IDE - v0.19.0"
#      url: https://github.com/alexoooo/kzen-project/releases/download/v0.19.0/kzen-project-0.19.0.zip

    - name: KzenProjectJar-0.24.0
      title: "Automation and Reporting"
      description: "Visually control a browser and more - v0.24.0"
      url: https://github.com/alexoooo/kzen-project/releases/download/v0.24.0/kzen-project-0.24.0.jar

    - name: KzenProjectZip-0.24.0
      title: "Automation and Reporting (with Scripting)"
      description: "Includes source code, can be used with IDE - v0.24.0"
      url: https://github.com/alexoooo/kzen-project/releases/download/v0.24.0/kzen-project-0.24.0.zip

