
kzen:
  archetypes:
    - name: KzenProjectJar-0.4.1
      title: "Desktop Automation"
      description: "Visually control a browser and more - v0.4.1"
      url: https://github.com/alexoooo/kzen-project/releases/download/v0.4.1/kzen-project-jvm-0.4.1.jar

    - name: KzenProjectZip-0.4.1
      title: "Desktop Automation with Scripting"
      description: "Includes source code, can be used with IDE - v0.4.1"
      url: https://github.com/alexoooo/kzen-project/releases/download/v0.4.1/kzen-project-0.4.1.zip

