const val kotlinVersion = "1.5.0"
const val jvmTargetVersion = "16"
const val springBootVersion = "2.4.5"
const val dependencyManagementVersion = "1.0.11.RELEASE"

const val coroutinesVersion = "1.5.0-RC"

const val logbackVersion = "1.2.3"
const val guavaVersion = "30.1.1-jre"
const val commonsCompressVersion = "1.20"
const val jacksonModuleKotlin = "2.12.1"
const val jacksonDataformatYaml = "2.12.1"

const val coreJsVersion = "3.11.2"
const val reactVersion = "17.0.2"
const val inlineStylePrefixerVersion = "6.0.0"
const val styledComponentsVersion = "5.2.3"
const val kotlinHtmlVersion = "0.7.3"
const val materialUiCoreVersion = "4.11.3"
const val materialUiIconsVersion = "4.11.2"
const val reactSelectVersion = "4.3.0"

const val wrapperKotlinVersion = "pre.154-kotlin-1.5.0"
const val kotlinReactVersion = "17.0.2-$wrapperKotlinVersion"
const val kotlinReactDomVersion = "17.0.2-$wrapperKotlinVersion"
const val kotlinStyledVersion = "5.2.3-$wrapperKotlinVersion"
const val kotlinExtensionsVersion = "1.0.1-$wrapperKotlinVersion"
const val kotlinCssVersion = "1.0.0-$wrapperKotlinVersion"